"use client";

import Link from "next/link";
import { useMemo } from "react";
import { useBudget } from "@/lib/store";
import { auditerDepenses } from "@/lib/audit";
import { euros } from "@/lib/format";

export default function AbonnementsPage() {
  const { transactions, recurrentes, profil } = useBudget();
  const audit = useMemo(() => auditerDepenses({ transactions, recurrentes }, { revenuMensuel: profil.revenuMensuel || 0 }), [transactions, recurrentes, profil.revenuMensuel]);
  return <div className="space-y-5"><header><p className="text-v3-caption font-semibold uppercase tracking-[.14em] text-marque">Récurrences détectées</p><h1 className="mt-1 text-3xl font-bold tracking-tight">Abonnements</h1><p className="mt-2 text-sm leading-5 text-sourdine">Un endroit pour visualiser le coût réel de tes prélèvements et décider quoi garder.</p></header><section className="rounded-v3-l bg-[linear-gradient(145deg,#1f2937,#334155)] p-5 text-white shadow-v3-medium"><p className="text-sm text-white/70">Coût estimé</p><p className="tnum mt-1 text-4xl font-bold">{euros(audit.totalMensuel)}<span className="text-lg text-white/60"> / mois</span></p><p className="mt-3 border-t border-white/15 pt-3 text-sm text-white/75">{euros(audit.totalAnnuel)} par an · {audit.items.length} prélèvement{audit.items.length > 1 ? "s" : ""} identifié{audit.items.length > 1 ? "s" : ""}</p></section>{audit.economiePotentielle > 0 && <section className="rounded-v3-m bg-menthe-pale p-4"><strong className="block text-menthe-texte">Potentiel : {euros(audit.economieAnnuelle)} / an</strong><p className="mt-1 text-sm text-menthe-texte">En vérifiant les doublons et services possiblement oubliés.</p></section>}<section><h2 className="mb-2 font-semibold">À examiner</h2><div className="space-y-2">{audit.items.length ? audit.items.map((item, index) => <Link key={`${item.libelle}-${index}`} href={`/transactions?recherche=${encodeURIComponent(item.libelle)}`} className="flex items-center gap-3 rounded-v3-m bg-ui-surface-floating p-3.5 shadow-v3-soft"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-ui-surface-raised text-lg">{item.abonnement?.icone || "🔁"}</span><span className="min-w-0 flex-1"><strong className="block truncate text-sm">{item.libelle}</strong><span className="block text-xs text-sourdine">{item.dormant ? "À vérifier : plus prélevé récemment" : item.famille?.label || "Prélèvement récurrent"}</span></span><strong className="tnum text-sm">{euros(item.montantMensuel)}</strong></Link>) : <p className="rounded-v3-m bg-ui-surface-floating p-4 text-sm text-sourdine shadow-v3-soft">Aucun abonnement détecté : ajoute deux mois d’historique pour améliorer la détection.</p>}</div></section><Link href="/regles" className="block rounded-v3-m bg-marque-pale p-4 text-sm font-semibold text-marque-texte">Créer une règle pour classer automatiquement ces opérations ›</Link></div>;
}
