"use client";

import { useState } from "react";
import { useBudget } from "@/lib/store";

export default function ReglesPage() {
  const { profil, categories, sauverApp, transactions } = useBudget();
  const [mot, setMot] = useState(""); const [categorie, setCategorie] = useState("courses");
  const regles = profil.reglesAuto || [];
  const ajouter = async () => { if (mot.trim().length < 2) return; await sauverApp(undefined, { ...profil, reglesAuto: [...regles, { id: `regle-${Date.now().toString(36)}`, mot: mot.trim(), categorie }] }); setMot(""); };
  const retirer = async (id) => sauverApp(undefined, { ...profil, reglesAuto: regles.filter((regle) => regle.id !== id) });
  const apercu = mot.trim().length >= 2 ? transactions.filter((tx) => (tx.libelle || "").toLocaleLowerCase("fr").includes(mot.trim().toLocaleLowerCase("fr"))).length : 0;
  return <div className="space-y-5"><header><p className="text-v3-caption font-semibold uppercase tracking-[.14em] text-marque">Automatisations lisibles</p><h1 className="mt-1 text-3xl font-bold tracking-tight">Règles</h1><p className="mt-2 text-sm leading-5 text-sourdine">Quand un libellé correspond, Pécule lui attribue automatiquement la bonne catégorie.</p></header><section className="rounded-v3-l bg-ui-surface-floating p-4 shadow-v3-soft"><h2 className="font-semibold">Nouvelle règle</h2><label className="mt-3 block text-xs font-semibold uppercase tracking-wide text-sourdine">Si le libellé contient</label><input value={mot} onChange={(event) => setMot(event.target.value)} placeholder="Ex. Netflix ou Carrefour" className="mt-1 w-full rounded-v3-s border border-ui-hairline bg-ui-surface-raised px-3 py-3 outline-none focus:border-marque" /><label className="mt-3 block text-xs font-semibold uppercase tracking-wide text-sourdine">Alors classer dans</label><select value={categorie} onChange={(event) => setCategorie(event.target.value)} className="mt-1 w-full rounded-v3-s border border-ui-hairline bg-ui-surface-raised px-3 py-3">{Object.entries(categories).filter(([, value]) => value.type !== "virement").map(([id, value]) => <option key={id} value={id}>{value.icone} {value.label}</option>)}</select>{mot.trim().length >= 2 && <p className="mt-2 text-xs text-sourdine">Cette règle correspondrait à {apercu} opération{apercu > 1 ? "s" : ""} déjà présente{apercu > 1 ? "s" : ""}.</p>}<button onClick={ajouter} disabled={mot.trim().length < 2} className="mt-4 w-full rounded-v3-s bg-marque-bouton py-3 text-sm font-semibold text-surMarque disabled:opacity-40">Créer la règle</button></section><section><div className="mb-2 flex justify-between"><h2 className="font-semibold">Règles actives</h2><span className="text-sm text-sourdine">{regles.length}</span></div><div className="space-y-2">{regles.length ? regles.map((regle) => <div key={regle.id} className="flex items-center gap-3 rounded-v3-m bg-ui-surface-floating p-3.5 shadow-v3-soft"><span className="text-xl">{categories[regle.categorie]?.icone || "🏷️"}</span><span className="min-w-0 flex-1"><strong className="block text-sm">« {regle.mot} »</strong><span className="block text-xs text-sourdine">→ {categories[regle.categorie]?.label || "Catégorie"}</span></span><button onClick={() => retirer(regle.id)} className="rounded-pill bg-corail-pale px-2.5 py-1.5 text-xs font-semibold text-corail-texte">Retirer</button></div>) : <p className="rounded-v3-m bg-ui-surface-floating p-4 text-sm text-sourdine shadow-v3-soft">Aucune règle pour le moment.</p>}</div></section></div>;
}
